# Generated by Django 6.0.4 on 2026-04-27 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_remove_employee_email_remove_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedata',
            name='billing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='models.billing'),
        ),
    ]
