# Generated by Django 6.0.4 on 2026-04-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=60)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('customerType', models.CharField(choices=[('Purchase', 'Purchase'), ('Service', 'Service'), ('Visit', 'Visit')], default='Service', max_length=8)),
            ],
        ),
    ]
